import type { SandPreset, SandPresetName } from "@/motion/sand/types";

export const sandPresets: Record<SandPresetName, SandPreset> = {
  faint: {
    density: 1,
    layers: [
      {
        id: "near",
        count: 58,
        duration: 86,
        size: { min: 1.1, max: 2.2 },
        opacity: { min: 0.18, max: 0.34 },
        drift: { from: -6, to: 8, sway: 0.6 },
        blur: 0,
      },
      {
        id: "mid",
        count: 40,
        duration: 112,
        size: { min: 0.95, max: 1.85 },
        opacity: { min: 0.14, max: 0.28 },
        drift: { from: -8, to: 10, sway: 0.8 },
        blur: 0.18,
      },
      {
        id: "far",
        count: 26,
        duration: 136,
        size: { min: 0.86, max: 1.5 },
        opacity: { min: 0.11, max: 0.22 },
        drift: { from: -10, to: 12, sway: 1 },
        blur: 0.32,
      },
    ],
  },
  subtle: {
    density: 1.35,
    layers: [
      {
        id: "near",
        count: 72,
        duration: 74,
        size: { min: 1.25, max: 2.45 },
        opacity: { min: 0.22, max: 0.4 },
        drift: { from: -7, to: 9, sway: 0.7 },
        blur: 0,
      },
      {
        id: "mid",
        count: 52,
        duration: 98,
        size: { min: 1.05, max: 2 },
        opacity: { min: 0.16, max: 0.3 },
        drift: { from: -9, to: 11, sway: 0.9 },
        blur: 0.2,
      },
      {
        id: "far",
        count: 36,
        duration: 126,
        size: { min: 0.92, max: 1.7 },
        opacity: { min: 0.12, max: 0.24 },
        drift: { from: -11, to: 13, sway: 1.1 },
        blur: 0.36,
      },
    ],
  },
  soft: {
    density: 1.58,
    layers: [
      {
        id: "near",
        count: 96,
        duration: 62,
        size: { min: 1.4, max: 2.8 },
        opacity: { min: 0.3, max: 0.56 },
        drift: { from: -8, to: 10, sway: 0.8 },
        blur: 0,
      },
      {
        id: "mid",
        count: 68,
        duration: 86,
        size: { min: 1.1, max: 2.25 },
        opacity: { min: 0.2, max: 0.38 },
        drift: { from: -10, to: 12, sway: 1 },
        blur: 0.12,
      },
      {
        id: "far",
        count: 44,
        duration: 108,
        size: { min: 0.96, max: 1.9 },
        opacity: { min: 0.14, max: 0.3 },
        drift: { from: -12, to: 14, sway: 1.2 },
        blur: 0.26,
      },
    ],
  },
};
