import type { SandPreset, SandPresetName } from "@/motion/sand/types";

export const sandPresets: Record<SandPresetName, SandPreset> = {
  faint: {
    density: 1,
    layers: [
      {
        id: "near",
        count: 58,
        duration: 86,
        size: { min: 1.1, max: 2.2 },
        opacity: { min: 0.18, max: 0.34 },
        drift: { from: -6, to: 8, sway: 0.6 },
        gust: {
          keyframes: 8,
          jitter: 1.8,
          verticalNoise: 0.5,
          opacityBoost: 0.26,
          timingVariance: 0.5,
        },
        grainMotion: {
          wobbleX: { min: 0.14, max: 0.36 },
          wobbleY: { min: 0.12, max: 0.3 },
          wobbleDuration: { min: 7.8, max: 11.6 },
          pulseDuration: { min: 6.4, max: 10.1 },
          pulseScale: { min: 1.04, max: 1.16 },
        },
        blur: 0,
      },
      {
        id: "mid",
        count: 40,
        duration: 112,
        size: { min: 0.95, max: 1.85 },
        opacity: { min: 0.14, max: 0.28 },
        drift: { from: -8, to: 10, sway: 0.8 },
        gust: {
          keyframes: 7,
          jitter: 1.5,
          verticalNoise: 0.6,
          opacityBoost: 0.22,
          timingVariance: 0.52,
        },
        grainMotion: {
          wobbleX: { min: 0.1, max: 0.28 },
          wobbleY: { min: 0.1, max: 0.24 },
          wobbleDuration: { min: 8.6, max: 12.4 },
          pulseDuration: { min: 7.2, max: 11.6 },
          pulseScale: { min: 1.03, max: 1.12 },
        },
        blur: 0.18,
      },
      {
        id: "far",
        count: 26,
        duration: 136,
        size: { min: 0.86, max: 1.5 },
        opacity: { min: 0.11, max: 0.22 },
        drift: { from: -10, to: 12, sway: 1 },
        gust: {
          keyframes: 6,
          jitter: 1.2,
          verticalNoise: 0.7,
          opacityBoost: 0.2,
          timingVariance: 0.48,
        },
        grainMotion: {
          wobbleX: { min: 0.08, max: 0.22 },
          wobbleY: { min: 0.08, max: 0.2 },
          wobbleDuration: { min: 9.4, max: 13.8 },
          pulseDuration: { min: 8.3, max: 12.8 },
          pulseScale: { min: 1.02, max: 1.1 },
        },
        blur: 0.32,
      },
    ],
  },
  subtle: {
    density: 1.35,
    layers: [
      {
        id: "near",
        count: 72,
        duration: 74,
        size: { min: 1.25, max: 2.45 },
        opacity: { min: 0.22, max: 0.4 },
        drift: { from: -7, to: 9, sway: 0.7 },
        gust: {
          keyframes: 9,
          jitter: 2.2,
          verticalNoise: 0.74,
          opacityBoost: 0.32,
          timingVariance: 0.6,
        },
        grainMotion: {
          wobbleX: { min: 0.18, max: 0.48 },
          wobbleY: { min: 0.16, max: 0.42 },
          wobbleDuration: { min: 7.2, max: 10.8 },
          pulseDuration: { min: 6.1, max: 9.2 },
          pulseScale: { min: 1.07, max: 1.22 },
        },
        blur: 0,
      },
      {
        id: "mid",
        count: 52,
        duration: 98,
        size: { min: 1.05, max: 2 },
        opacity: { min: 0.16, max: 0.3 },
        drift: { from: -9, to: 11, sway: 0.9 },
        gust: {
          keyframes: 8,
          jitter: 1.9,
          verticalNoise: 0.82,
          opacityBoost: 0.28,
          timingVariance: 0.58,
        },
        grainMotion: {
          wobbleX: { min: 0.14, max: 0.38 },
          wobbleY: { min: 0.14, max: 0.34 },
          wobbleDuration: { min: 8, max: 11.8 },
          pulseDuration: { min: 6.8, max: 10.3 },
          pulseScale: { min: 1.05, max: 1.18 },
        },
        blur: 0.2,
      },
      {
        id: "far",
        count: 36,
        duration: 126,
        size: { min: 0.92, max: 1.7 },
        opacity: { min: 0.12, max: 0.24 },
        drift: { from: -11, to: 13, sway: 1.1 },
        gust: {
          keyframes: 7,
          jitter: 1.5,
          verticalNoise: 0.92,
          opacityBoost: 0.24,
          timingVariance: 0.54,
        },
        grainMotion: {
          wobbleX: { min: 0.1, max: 0.3 },
          wobbleY: { min: 0.1, max: 0.28 },
          wobbleDuration: { min: 9, max: 12.8 },
          pulseDuration: { min: 7.6, max: 11.6 },
          pulseScale: { min: 1.04, max: 1.14 },
        },
        blur: 0.36,
      },
    ],
  },
  soft: {
    density: 1.76,
    layers: [
      {
        id: "near",
        count: 108,
        duration: 54,
        size: { min: 1.45, max: 2.9 },
        opacity: { min: 0.32, max: 0.58 },
        drift: { from: -14, to: 18, sway: 1.25 },
        gust: {
          keyframes: 12,
          jitter: 4.1,
          verticalNoise: 1.18,
          opacityBoost: 0.42,
          timingVariance: 0.78,
        },
        grainMotion: {
          wobbleX: { min: 0.34, max: 0.9 },
          wobbleY: { min: 0.28, max: 0.74 },
          wobbleDuration: { min: 5.2, max: 8.4 },
          pulseDuration: { min: 4.6, max: 7.8 },
          pulseScale: { min: 1.12, max: 1.35 },
        },
        blur: 0,
      },
      {
        id: "mid",
        count: 78,
        duration: 76,
        size: { min: 1.15, max: 2.3 },
        opacity: { min: 0.22, max: 0.4 },
        drift: { from: -16, to: 20, sway: 1.35 },
        gust: {
          keyframes: 11,
          jitter: 3.4,
          verticalNoise: 1.06,
          opacityBoost: 0.36,
          timingVariance: 0.72,
        },
        grainMotion: {
          wobbleX: { min: 0.24, max: 0.62 },
          wobbleY: { min: 0.2, max: 0.52 },
          wobbleDuration: { min: 6.6, max: 9.6 },
          pulseDuration: { min: 5.5, max: 8.8 },
          pulseScale: { min: 1.1, max: 1.3 },
        },
        blur: 0.1,
      },
      {
        id: "far",
        count: 52,
        duration: 96,
        size: { min: 0.98, max: 2 },
        opacity: { min: 0.15, max: 0.32 },
        drift: { from: -18, to: 22, sway: 1.55 },
        gust: {
          keyframes: 10,
          jitter: 2.8,
          verticalNoise: 1.2,
          opacityBoost: 0.32,
          timingVariance: 0.65,
        },
        grainMotion: {
          wobbleX: { min: 0.18, max: 0.52 },
          wobbleY: { min: 0.16, max: 0.46 },
          wobbleDuration: { min: 7.2, max: 10.5 },
          pulseDuration: { min: 6.3, max: 9.8 },
          pulseScale: { min: 1.08, max: 1.24 },
        },
        blur: 0.22,
      },
    ],
  },
};
